VM_GROUP_NAME='/portfolio_jenkins_edtool'

Vagrant.configure("2") do |config|

  # ------------------------------
  # master
  # ------------------------------
  config.vm.define "jenkins" do |master|
    master.vm.box = "ubuntu/focal64"
    master.vm.hostname = "jenkins"
    master.vm.network "private_network", ip: "192.168.56.100"

    master.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", VM_GROUP_NAME]
    end

    # install java + jenkins
    master.vm.provision "shell", inline: <<-SHELL
      curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jre
      sudo apt-get install -y jenkins
    SHELL
  end

  # ------------------------------
  # node1 (npm, ui5 tooling)
  # ------------------------------
  config.vm.define "node1" do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "192.168.56.101"

    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", VM_GROUP_NAME]
    end

    # install java, npm, ui5, jenkins_workdir
    node.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jre
      sudo apt-get install -y npm
      sudo npm install --global @ui5/cli
      mkdir /home/vagrant/jenkins_workdir
      sudo chown vagrant:vagrant jenkins_workdir
    SHELL
  end

end
